Add basic CORS config and api health endpoint
Bodzisz/ZPI-backend pull request #3
Opened 2023-10-10 15:57 UTC by Bodzisz

2023-10-10 16:21 UTC, FilipBrzeziak commented on src/main/resources/application.properties
Dlaczego usunąłeś application.properties? imo application.properties sa bardziej czytelne niz yml

2023-10-10 16:21 UTC, FilipBrzeziak requested changes
Mozemy wrocic do application.properties?

2023-10-10 16:24 UTC, Bodzisz commented on src/main/resources/application.properties
Imo nie XD. Jak masz więcej zagnieżdżonych propertiesów to strasznie słabo to wygląda i trudno dojść co jest pod czym. Poza tym w yamlu masz więcej supportowanych danych. Myślę, że trochę tego configu będzie u nas i warto zostać przy yml ;)

2023-10-16 21:01 UTC, FilipBrzeziak commented on src/main/resources/application.properties
Niech strace ;)

2023-10-16 21:01 UTC, FilipBrzeziak approved these changes

2023-10-16 21:01 UTC, merged